Added Quick Start Guide Documentation
ni/niveristand-instrument-addon-custom-device pull request #112
Opened 2020-09-29 11:50 UTC by csteavu

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Added Quick Start Guide Documentation markdown file.
The file contains: 

- the information from the html quick start

- the Scripting API information

- examples for the Scripting API

### Why should this Pull Request be merged?

Html Quick Start Guide did not contain the Scripting API information;

### What testing has been done?

Visual Check of the MD file

2020-09-30 09:03 UTC, bogdanp-ni commented
Please remove the old docs and update the links (from Main Page Help and README.md) to point to the new Markdown docs.

2020-09-30 09:08 UTC, bogdanp-ni approved these changes
I'm ok with this, as long as the links are fixed (see prev. comment).

2020-09-30 11:39 UTC, phutanu commented on Quick Start Documentation/Instrument Addon Quick Start Guide.md
> +    Node used: **Create Instrument Addon**
A new line needs to be added here for better rendering and consistency with the other examples.

2020-09-30 11:39 UTC, phutanu commented on Quick Start Documentation/Instrument Addon Quick Start Guide.md
> +- create a new Instrument from scratch<br/>
A new line needs to be added here for better rendering and consistency with the other examples.

2020-09-30 11:43 UTC, phutanu commented on Quick Start Documentation/Instrument Addon Quick Start Guide.md
> +![Create Global MetaData Channel](./Images/image046.png)
image46.png needs to be updated to show all the different types of Data Channels allowed. Currently it shows only one: Single Channel Enumerated List.

![image](https://user-images.githubusercontent.com/62251693/94680917-3a359800-032b-11eb-8bdf-5d1883771772.png)

2020-09-30 11:51 UTC, phutanu commented on Quick Start Documentation/Instrument Addon Quick Start Guide.md
> +
This rendering does not look consistent.

![image](https://user-images.githubusercontent.com/62251693/94681469-2cccdd80-032c-11eb-843a-704adecf845e.png)

We can change the description to something like: "Nodes used: **Get PCL Decimation** and **Set PCL Decimation**" and do the same thing the Get Protocol and Set Protocol.

2020-09-30 11:54 UTC, phutanu commented on Quick Start Documentation/Instrument Addon Quick Start Guide.md
> +A Protocol object is needed as input when creating a new Instrument Addon<br/>
A new line is needed here for better rendering.

2020-09-30 11:58 UTC, phutanu commented on Quick Start Documentation/Instrument Addon Quick Start Guide.md
> +![Factories](./Images/image052.png)
For whatever reason the above line is rendered different than the other lines. This breaks the consistency of the file.

![image](https://user-images.githubusercontent.com/62251693/94682284-5fc3a100-032d-11eb-9c2d-dd38359634c6.png)

2020-09-30 12:04 UTC, phutanu commented
[Recommendation] what do you think if we replace the "Settings" typedef control input with a "Settings" constant?
This will be helpful for the users to see what settings are available for each node type and polymorphic instance.

2020-09-30 12:05 UTC, phutanu requested changes
Please check my above comments.

2020-10-01 11:41 UTC, csteavu commented
> [Recommendation] what do you think if we replace the "Settings" typedef control input for all the Scripting single nodes from the section "With this API, users can:" with a "Settings" constant?
> I put this as a recommendation because I know it will take a lot of work, as we need to update a lot of png files.
> This change will be helpful for the users to see what settings are available for each node type and polymorphic instance.
> 
> Like the examples from the Scripting API HLD Doc:
> ![image](https://user-images.githubusercontent.com/62251693/94683494-4de2fd80-032f-11eb-964f-fb35048c6acd.png)

This recommendation brings a lot of value. As discussed offline, this will be implemented along with the rework that will arise from the API Review

2020-10-01 11:45 UTC, bogdanp-ni commented
> > [Recommendation] what do you think if we replace the "Settings" typedef control input for all the Scripting single nodes from the section "With this API, users can:" with a "Settings" constant?
> > I put this as a recommendation because I know it will take a lot of work, as we need to update a lot of png files.
> > This change will be helpful for the users to see what settings are available for each node type and polymorphic instance.
> > Like the examples from the Scripting API HLD Doc:
> > ![image](https://user-images.githubusercontent.com/62251693/94683494-4de2fd80-032f-11eb-964f-fb35048c6acd.png)
> 
> This recommendation brings a lot of value. As discussed offline, this will be implemented along with the rework that will arise from the API Review

+1 for this getting added with the API review fixes, but please add another task specifically for this request. Otherwise, it will be lost in the multitude of small updates we'll have to do.

2020-10-01 14:02 UTC, phutanu commented on Quick Start Documentation/Instrument Addon Quick Start Guide.md
> +- create a new Instrument from scratch<br/>
I'm ok with the changes, but just a new line here would make a huge visual difference.

![image](https://user-images.githubusercontent.com/62251693/94819314-c7e6b580-0407-11eb-870f-83256dd93bbd.png)

2020-10-01 14:05 UTC, phutanu approved these changes
> I'm ok with the changes, but just a new line where the red arrow is would make a huge visual difference.
> 
> ![image](https://user-images.githubusercontent.com/62251693/94819314-c7e6b580-0407-11eb-870f-83256dd93bbd.png)

2020-10-01 19:25 UTC, merged