Refactor SE functionality after adding MetaData Channels scripting support
ni/niveristand-instrument-addon-custom-device pull request #116
Opened 2020-10-01 11:40 UTC by bogdanp-ni

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Refactor System Explorer by leveraging MetaData Channels scripting support.

### Why should this Pull Request be merged?

Reduces duplication, consolidating backend logic into scripting library.

### What testing has been done?

Local build and manual testing.

2020-10-01 11:41 UTC, bogdanp-ni commented
Marked as draft, as it is dependent on another PR (https://github.com/ni/niveristand-instrument-addon-custom-device/pull/115).

2020-10-02 09:03 UTC, phutanu commented
Add New MetaData Array.vi & Add New MetaData Channel.vi

- the "Assign New GUID to Refnum.vi" should be removed from the FP of both VIs as this node is already called inside the "Create MetaData Element.vi".

![image](https://user-images.githubusercontent.com/62251693/94906287-ddf78300-04a6-11eb-8e89-32e76814e213.png)
![image](https://user-images.githubusercontent.com/62251693/94906370-07b0aa00-04a7-11eb-9dfc-b182a0468cdb.png)

2020-10-02 09:06 UTC, phutanu commented
I know we do not have yet a code guideline for how block diagrams should look like but I would like to see all the terminals viewed as icons for the below VI as this will improve greatly the readability.
![image](https://user-images.githubusercontent.com/62251693/94906699-a0dfc080-04a7-11eb-9482-79034fb3d16a.png)

2020-10-02 09:15 UTC, phutanu commented
MetaData Channel.vi ->I do not want to be nitpicking and I also know you didn't touch this specific event cases, but during the refactoring and resizing the visual aspect of the code was affected. Could you please adjust this?

![image](https://user-images.githubusercontent.com/62251693/94907365-b86b7900-04a8-11eb-97f6-aa103caf7441.png)
![image](https://user-images.githubusercontent.com/62251693/94907443-db962880-04a8-11eb-9e71-d9c4dbb17fea.png)

2020-10-02 09:17 UTC, phutanu commented on Source/Addon/Addon System Explorer/Instrument Addon System Explorer.lvlib
> +	<Item Name="Build Array Elements.vi" Type="VI" URL="../SubVIs/Build Array Elements.vi"/>
This subVI should go under the "SubVIs" folder in the System Explorer.lvlib.

2020-10-02 09:17 UTC, phutanu requested changes
Please check my above comments.

2020-10-02 12:04 UTC, bogdanp-ni commented
> MetaData Channel.vi -> I do not want to be nitpicking and I also know you didn't touch this specific event cases, but during the refactoring and resizing the visual aspect of the code was affected. Could you please adjust this?
> 
> ![image](https://user-images.githubusercontent.com/62251693/94907365-b86b7900-04a8-11eb-97f6-aa103caf7441.png)
> ![image](https://user-images.githubusercontent.com/62251693/94907443-db962880-04a8-11eb-9e71-d9c4dbb17fea.png)

This makes a lot of sense :) I messed them up while rescaling the other event cases. Thanks!

2020-10-02 12:51 UTC, phutanu approved these changes

2020-10-02 12:51 UTC, merged