Re-arranged the controls/indicators on the Front Pannel. Formated the … block diagram. fixed the input/output naming according to the new standards. Added description to the VI.
ni/niveristand-instrument-addon-custom-device pull request #122
Opened 2020-10-06 16:24 UTC by zszilagy

- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

The following was updated in this VI:

- Arranged Front Panel with Ctrl+Space,Ctrl+F
- Arranged Block Diagram with Ctrl+Space,Ctrl+F
- Changed control/indicator label to lower case letters
- Added description to the VI

### Why should this Pull Request be merged?

The current version of the VI does not meet the design guidelines.

### What testing has been done?

n/a

2020-10-06 18:03 UTC, phutanu approved these changes

2020-10-07 06:59 UTC, bogdanp-ni commented
Small "i" here:

![image](https://user-images.githubusercontent.com/61490253/95297877-d3acfe80-0883-11eb-8494-8c6b195ed2a2.png)

2020-10-07 07:00 UTC, bogdanp-ni requested changes
See my comment

2020-10-07 09:09 UTC, zszilagy commented
> Small "i" here:
> 
> ![image](https://user-images.githubusercontent.com/61490253/95297877-d3acfe80-0883-11eb-8494-8c6b195ed2a2.png)

fixed.

2020-10-07 13:35 UTC, bogdanp-ni approved these changes

2020-10-07 13:43 UTC, merged