Updated Quick Start Guide and changed text color in both Get and Set Protocol Icons
ni/niveristand-instrument-addon-custom-device pull request #146
Opened 2020-10-20 16:35 UTC by csteavu

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Updated Quick Start Guide
- Changed text color in both Get and Set Protocol Icons

### Why should this Pull Request be merged?

- Quick Start Guide was out of date
- Text color in both Get and Set Protocol Icons was different than all other icons

### What testing has been done?

N/A

2020-10-20 20:39 UTC, phutanu requested changes
Except these two small change, I'm ok with the change.

2020-10-21 06:10 UTC, csteavu commented on Source/Quick Start Documentation/Instrument Addon Quick Start Guide.md
> +
fixed

2020-10-21 06:10 UTC, csteavu commented on Source/Quick Start Documentation/Instrument Addon Quick Start Guide.md
> +- Create and configure a protocol<br/>
fixed

2020-10-21 06:41 UTC, phutanu approved these changes

2020-10-21 06:57 UTC, bogdanp-ni approved these changes

2020-10-21 06:57 UTC, merged