Fixed command/response deletion issue
ni/niveristand-instrument-addon-custom-device pull request #153
Opened 2020-10-26 12:44 UTC by zszilagy

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Fixed the issue where removing all Metadata/Data Channels also deleted the Command/Response section from the instrument addon. (System Explorer)

### Why should this Pull Request be merged?

Currently, when all Data/Metadata Channels are removed from the Response/Command section the section is also removed.

### What testing has been done?

Built the Custom Device using the updated xml document. Added a new IA CD in the system explorer and then Message Group->Message. Under Command/Response added Metadata Channels/Data Channels. Right click each section and selected the "Delete Multiple Items" option selecting all channels under the section. After the deletion the sections were not removed.

2020-10-26 12:50 UTC, phutanu approved these changes

2020-10-27 06:30 UTC, bogdanp-ni commented
Can I still delete a particular Command or Response (r-click on it, then select Delete)? That workflow is still needed for configuring Command-only/Response-only Messages.

2020-10-27 06:31 UTC, bogdanp-ni requested changes
Blocking to make sure another workflow is not affected by this change - see my previous comment.

2020-10-27 09:38 UTC, zszilagy commented
> Can I still delete a particular Command or Response (r-click on it, then select Delete)? That workflow is still needed for configuring Command-only/Response-only Messages.

Yes. It works just as before. The XML does not prevent the section to be deleted when the delete option is selected.

2020-10-27 10:13 UTC, bogdanp-ni approved these changes

2020-10-27 10:13 UTC, merged