Made all the modifications required to have a standalone examples package
ni/niveristand-instrument-addon-custom-device pull request #171
Opened 2021-05-04 10:16 UTC by zszilagy

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Creates a standalong nipkg file for the Scripting API Examples project.

### Why should this Pull Request be merged?

Currently the examples doesn't come in a separate nipkg.

### What testing has been done?
n/a. Will be verified after the first PR installers are built.

2021-05-04 11:44 UTC, phutanu commented on control_scripting_examples
> +Description: Provides exmaples for LabVIEW support for the Instrument Addon custom device for NI VeriStand {veristand_version}.
examples

2021-05-04 13:19 UTC, phutanu commented
> Bleep bloop!
> 
> LabVIEW Diff Robot here with some diffs served up hot for your pull request.
> 
> Notice something funny? Help fix me on [my GitHub repo.](https://github.com/ni/niveristand-custom-device-build-tools)
> 
> Post-Build Action.vi.png
> ![capture](https://raw.githubusercontent.com/niveristand-diff-bot/diff-images/master/NI/niveristand-instrument-addon-custom-device/PR-171/2021-05-04/06%3A24%3A57/Post-Build%20Action.vi.png)

I think this setup will generate a nested structures like:
- "Scripting Examples/Scripting API Examples/..." in the Destination Path.

Shouldn't we use the same mechanism like for the other assets without adding the extra code for path manipulation?

2021-05-04 13:31 UTC, phutanu requested changes
Please check my above comment.

2021-05-05 08:17 UTC, bogdanp-ni approved these changes

2021-05-05 08:20 UTC, phutanu approved these changes

2021-05-05 08:22 UTC, merged