IA -> Add Response ByteCount & Wait(sec) implementation
ni/niveristand-instrument-addon-custom-device pull request #97
Opened 2020-09-14 14:03 UTC by DStavilaNI

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Implementation of the Add Response - Wait(sec).vi
- Implementation of the Add Response - ByteCount.vi
- Implementation of the Test VIs

### Why should this Pull Request be merged?

- Implements the "Add Response API" and and corresponding tests

### What testing has been done?

- Implemented test VIs for the created API
- Testing on the local DEV machine has been done

2020-09-15 09:42 UTC, bogdanp-ni commented
There are some tests where the "TestCase out" is unwired. Please wire them accordingly.

2020-09-15 09:47 UTC, bogdanp-ni commented
For improving readability, please wire the same constant to these checks (as far as I understood, they should have the same value), instead od using two different ones (see below):

![image](https://user-images.githubusercontent.com/61490253/93195014-6a890e00-f751-11ea-86eb-020057960157.png)

2020-09-15 09:48 UTC, phutanu commented
Please remove the extra space at the end in the VI names for:
- Resolve Seconds Wait .vi
- Resolve ByteCount Wait .vi

2020-09-15 09:48 UTC, bogdanp-ni commented
[Recommend] Wherever possible, I suggest scaling the constant arrays being used, so that all elements are visible.

2020-09-15 09:57 UTC, bogdanp-ni commented
Parse Format String.vi -> this functionality is already present in the IA (Find Equation Variables.vi, in SE library). Please remove one of them, so that we don't have duplicated code.

2020-09-15 09:58 UTC, bogdanp-ni commented
Parse Format String.vi -> typo here:
![image](https://user-images.githubusercontent.com/61490253/93196435-1aab4680-f753-11ea-82d9-201c5986b438.png)

2020-09-15 09:59 UTC, phutanu commented
Please adjust the names for the below marked inputs. Please use one of the below options:
1. "Item Ref In" and "Item Ref Out"
2. "Message In" and "Message Out"

![image](https://user-images.githubusercontent.com/62251693/93195678-2248fc00-f70f-11ea-8ed9-62bd2671b7e9.png)

2020-09-15 10:13 UTC, bogdanp-ni commented
Resolve Response Linkaging.vi -> I must admit I'm having a hard time understanding the VI, mostly because of the multiple nested Case Structures. To improve readability, I would like you to make the following changes:
- the check for "empty Response" can be put in a separate subVI (throws error when empty), called right before Parse Format String, thus relying on the error chain to ensure correct execution
- a similar solution for checking that the array size from Parse Format String is 1
- the innermost functionality (see below) can be extracted in a subVI:
![image](https://user-images.githubusercontent.com/61490253/93198103-33b4f700-f755-11ea-93eb-fdc52615ece0.png)

2020-09-15 10:24 UTC, bogdanp-ni commented
Taking into consideration the fact that Add Response is linking variables with channel refnums (which is different from the UI logic), is there a way to utilize this scripting node (or some of its subVIs) directly in the UI part(SE lib)? In the long run, it will be very beneficial to remove as much duplication as possible, yielding a more lean and robust code.

2020-09-15 10:25 UTC, bogdanp-ni requested changes
Please see my comments above.

2020-09-15 10:28 UTC, phutanu commented
> For improving readability, please wire the same constant to these checks (as far as I understood, they should have the same value), instead od using two different ones (see below):
> 
> ![image](https://user-images.githubusercontent.com/61490253/93195014-6a890e00-f751-11ea-86eb-020057960157.png)

Also please correct the typo in the constant names: "Re**s**ponse Parameters".

2020-09-15 10:30 UTC, phutanu requested changes
Please check my above comments.

2020-09-16 08:34 UTC, DStavilaNI commented
> 
> 
> Please remove the extra space at the end in the VI names for:
> 
>     * Resolve Seconds Wait .vi
> 
>     * Resolve ByteCount Wait .vi

This is not recommended ?

2020-09-16 09:19 UTC, bogdanp-ni commented
> > Please remove the extra space at the end in the VI names for:
> > ```
> > * Resolve Seconds Wait .vi
> > 
> > * Resolve ByteCount Wait .vi
> > ```
> 
> This is not recommended ?

I don't know about phutanu, so I only speak for myself now, but unless there's a specific reason for that extra space (I thought it was a typo), I definitely like to see it fixed.

2020-09-16 09:55 UTC, DStavilaNI commented
> 
> 
> Resolve Response Linkaging.vi -> I must admit I'm having a hard time understanding the VI, mostly because of the multiple nested Case Structures. To improve readability, I would like you to make the following changes:
> 
>     * the check for "empty Response" can be put in a separate subVI (throws error when empty), called right before Parse Format String, thus relying on the error chain to ensure correct execution
> 
>     * a similar solution for checking that the array size from Parse Format String is 1
> 
>     * the innermost functionality (see below) can be extracted in a subVI:
>       ![image](https://user-images.githubusercontent.com/61490253/93198103-33b4f700-f755-11ea-93eb-fdc52615ece0.png)

Sure thing - I will refactor it to make it easier to understand

2020-09-16 09:56 UTC, DStavilaNI commented
> 
> 
> > > Please remove the extra space at the end in the VI names for:
> > > ```
> > > * Resolve Seconds Wait .vi
> > > 
> > > * Resolve ByteCount Wait .vi
> > > ```
> > 
> > 
> > This is not recommended ?
> 
> I don't know about phutanu, so I only speak for myself now, but unless there's a specific reason for that extra space (I thought it was a typo), I definitely like to see it fixed.

Sure

2020-09-16 10:10 UTC, DStavilaNI commented
> 
> 
> Taking into consideration the fact that Add Response is linking variables with channel refnums (which is different from the UI logic), is there a way to utilize this scripting node (or some of its subVIs) directly in the UI part(SE lib)? In the long run, it will be very beneficial to remove as much duplication as possible, yielding a more lean and robust code.

There are ways, but this would not be a simple copy&paste operation. I think extensive refactoring would be required in the SE and this would be a separate task/US.

2020-09-16 11:27 UTC, phutanu commented
[Recommendation] VI naming.
In order to improve API code reuse and readability inside project libraries I would suggest not using shorting in VI names.
VI in question: "Check LC&RF Size Equality.vi"

2020-09-16 11:29 UTC, phutanu requested changes
Please revert "Remove Target from Node Path.vi" as I suspect it was submitted by accident. No change was made to it.

2020-09-17 07:26 UTC, phutanu commented
> [Recommendation] VI naming.
> In order to improve API code reuse and readability inside project libraries I would suggest not using shorting in VI names.
> VI in question: "Check LC&RF Size Equality.vi"

For example this VI can be reused in the "Add Command" node. And that's why I would like it to have a verbose name.

2020-09-17 09:29 UTC, phutanu commented on Source/APIs/Scripting API/Instrument Addon Scripting API.lvlib
> +		<Item Name="Check LC&amp;RF Size Equality.vi" Type="VI" URL="../SubVIs/Check LC&amp;RF Size Equality.vi"/>
Please update also the Scripting API.lvlib with the new VI name.

2020-09-17 09:55 UTC, bogdanp-ni approved these changes
I approve the changes. Regarding the refactor in SE lib, please add another task under this US, which you can address in another follow-up PR.

2020-09-17 12:56 UTC, phutanu approved these changes

2020-09-17 12:57 UTC, merged